#!/usr/bin/env python3
"""Turn the Phase A results into the two artefacts the campaign exists to make.

  skills/evidence/reference-pipeline-2026-09.md   the campaign file: raw
      per-capture rows with scene names, cited and never matched against.
  skills/evidence/reference_profile.yaml          the machine-readable
      distribution the run-summary health digest normalises a new model against.

    tools/phase_a_report.py ~/sfm-phase-a-store/phase_a_results.json
"""
from __future__ import annotations

import argparse
import json
import statistics
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "packages" / "sfmkit" / "src"))
EVIDENCE = REPO / "skills" / "evidence"

# The rungs that go into the reference distribution, with the direction that is
# healthy. Both yield forms are carried: the corpus has not yet decided between
# them, and freezing one before it does would be the kind of premature cut point
# the whole corpus is written to avoid.
RUNGS = [
    ("registration", "higher_better", "registered frames / capture frames"),
    ("conditioning", "higher_better", "median widest triangulation angle, degrees"),
    ("composition", "higher_better", "share of points seen in more than two views"),
    ("coverage", "higher_better", "median per-frame occupied fraction of an 8x8 grid"),
    ("error", "lower_better", "median reprojection error among well-supported points, px"),
    ("yield_obs", "higher_better", "model observations / track observations"),
    ("yield_track", "higher_better", "model points / input tracks"),
    ("pose_agreement", "lower_better", "median |final relative rotation - two-view estimate|, degrees"),
]


def _spearman(xs, ys) -> float:
    """Rank correlation, written out rather than imported: sfmkit's dependency
    floor is numpy and nothing else, and a campaign report must not be the thing
    that adds scipy to this repository."""
    def ranks(v):
        order = sorted(range(len(v)), key=lambda i: v[i])
        out = [0.0] * len(v)
        i = 0
        while i < len(order):
            j = i
            while j + 1 < len(order) and v[order[j + 1]] == v[order[i]]:
                j += 1
            avg = (i + j) / 2.0 + 1.0          # mid-rank for ties
            for k in range(i, j + 1):
                out[order[k]] = avg
            i = j + 1
        return out

    rx, ry = ranks(xs), ranks(ys)
    n = len(rx)
    mx, my = sum(rx) / n, sum(ry) / n
    num = sum((a - mx) * (b - my) for a, b in zip(rx, ry))
    dx = sum((a - mx) ** 2 for a in rx) ** 0.5
    dy = sum((b - my) ** 2 for b in ry) ** 0.5
    return (num / (dx * dy)) if dx and dy else 0.0


def image_digests(store_root: Path, rows) -> dict[str, tuple[str, str]]:
    """module -> (image tag, digest) actually used, read from the artifacts.

    The campaign records this because a version tag does not pin behaviour: an
    image built before a code edit keeps its tag and keeps satisfying the
    artifact cache. The digest is the only field in the record that separates a
    row produced before a rebuild from one produced after.
    """
    try:
        from sfmkit import ArtifactStore
    except ImportError:
        return {}
    try:
        store = ArtifactStore(store_root)
    except Exception:
        return {}
    out = {}
    for r in rows:
        for aid in (r.get("artifacts") or {}).values():
            try:
                prov = store.open(aid).manifest.produced_by
            except Exception:
                continue
            if prov.module not in out:
                out[prov.module] = (prov.image, prov.image_digest)
    return out


def _vals(rows, key):
    out = []
    for r in rows:
        v = r.get("profile", {}).get(key)
        if isinstance(v, (int, float)) and v == v:      # finite, not NaN
            out.append(float(v))
    return out


def _fmt(v, n=3):
    if v is None or (isinstance(v, float) and v != v):
        return "—"
    if isinstance(v, float):
        return f"{v:.{n}f}".rstrip("0").rstrip(".") if abs(v) < 1000 else f"{v:.0f}"
    return str(v)


def reference_yaml(rows) -> str:
    lines = [
        "# The reference distribution of the seven-rung health profile.",
        "#",
        "# GENERATED by tools/phase_a_report.py from the reference campaign; the",
        "# per-capture rows and the protocol behind them are in",
        "# reference-pipeline-2026-09.md, which is the file to read before",
        "# trusting any number here.",
        "#",
        "# These are OBSERVED VALUES over a named corpus, never thresholds. A",
        "# reading outside the range below is outside what has been seen, which is",
        "# not the same as wrong: an extreme here is the largest or smallest of N",
        "# draws, and the next capture exceeding it is expected.",
        "#",
        "# With this many draws a percentile moves in coarse steps. Read the",
        "# profile as an ordering, not as a score.",
        "",
        f"campaign: reference-pipeline-2026-09",
        f"captures: {len(rows)}",
        "pipeline: FeatureDetectionSIFT -> FeatureMatchLightGlue (exhaustive) ->"
        " FeatureTrackUnionFind -> PoseEssentialToPnP -> SparseTriangulation ->"
        " BundleAdjustmentGlobal",
        "rungs:",
    ]
    for key, direction, meaning in RUNGS:
        vs = sorted(_vals(rows, key))
        if not vs:
            continue
        lines += [
            f"  {key}:",
            f"    direction: {direction}",
            f"    meaning: {meaning}",
            f"    n: {len(vs)}",
            f"    min: {vs[0]:.6g}",
            f"    median: {statistics.median(vs):.6g}",
            f"    max: {vs[-1]:.6g}",
            f"    values: [{', '.join(f'{v:.6g}' for v in vs)}]",
        ]
    floors = _vals(rows, "error_support_floor")
    if floors:
        lines += [
            "",
            "# The support floor the `error` rung was computed above, per capture.",
            "# A model's own median support is used when it is read outside this",
            "# corpus, which is stated in ladder.md rather than hidden here.",
            f"error_support_floor_median: {statistics.median(floors):.6g}",
        ]
    return "\n".join(lines) + "\n"


def campaign_md(rows, digests=None) -> str:
    ok = [r for r in rows if "profile" in r]
    failed = [r for r in rows if r.get("failed")]
    gt_rows = [r for r in ok if r.get("gt", {}).get("gt_pairs")]
    digests = digests or {}
    second = [r for r in ok if "second_solve" in r]
    kept_second = sum(1 for r in second
                      if (r["second_solve"] or {}).get("status") == "kept_second")
    second_lines = ([
        "Driven through the service, so where points escaped the pose stage the",
        "chain was re-solved at a wider window and the model recorded is the one",
        f"the service kept: the second solve on {kept_second} of {len(ok)} captures.",
        "",
    ] if second else [])
    # The digest is what separates a row produced before a rebuild from one
    # produced after; a tag does not. Collected, so written.
    image_lines = ([
        "## Images that produced these rows",
        "",
        "The campaign refuses to start unless every module image matches its",
        "source (`tools/image_drift.py`).",
        "",
        "| module | image | digest |",
        "| --- | --- | --- |",
        *[f"| {m} | `{img}` | `{(dg or '—')[:19]}` |"
          for m, (img, dg) in sorted(digests.items())],
        "",
    ] if digests else [])

    out = ["# Campaign: reference-pipeline-2026-09 — one pipeline, every corpus capture",
           "",
           "**This is a raw evidence table. Cite it; do not plan from it.** Every row is",
           "one capture driven through the same fixed pipeline at full frame count. The",
           "reasoning built on these rows lives in [`health/ladder.md`](../health/ladder.md)",
           "(the profile and what each rung means) and",
           "[`health/bounce.md`](../health/bounce.md) (what a persistently weak rung",
           "implies). A plan for a new capture cannot use a row from this table.",
           "",
           "## What ran",
           "",
           "```",
           "FeatureDetectionSIFT",
           "  -> FeatureMatchLightGlue   pairing: exhaustive",
           "  -> FeatureTrackUnionFind",
           "  -> PoseEssentialToPnP",
           "  -> SparseTriangulation",
           "  -> BundleAdjustmentGlobal",
           "```",
           "",
           "Every parameter at its module default except `pairing`, which is exhaustive so",
           "the view graph is not a function of frame ordering. Every image of every",
           "capture, at a 1024 px working resolution. **One recipe applied to every",
           "capture**: a reference corpus has to be fixed, or a percentile computed",
           "against it says which pipeline ran rather than how healthy a model is.",
           "",
           *second_lines,
           f"{len(ok)} captures reconstructed"
           + (f", {len(failed)} failed" if failed else "") + ".",
           "",
           *image_lines,
           "## The health profile, per capture",
           "",
           "`reg` = registered fraction. `cond` = median widest triangulation angle (deg).",
           "`comp` = share of points seen in more than two views. `cov` = median",
           "per-frame occupied fraction of an 8x8 grid. `err` = median reprojection",
           "error among well-supported points (px). `y_obs` / `y_trk` = observation-",
           "and track-yield. `pose` = median disagreement between the final relative",
           "rotations and the two-view estimates (deg).",
           "",
           "| capture | imgs | reg | cond | comp | cov | err | y_obs | y_trk | pose | points |",
           "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"]

    for r in sorted(ok, key=lambda r: r["capture"]):
        p = r["profile"]
        out.append("| {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |".format(
            r["capture"], p["n_images"], _fmt(p["registration"], 2),
            _fmt(p["conditioning"], 1), _fmt(p["composition"], 2),
            _fmt(p["coverage"], 2), _fmt(p["error"], 3), _fmt(p["yield_obs"], 3),
            _fmt(p["yield_track"], 3), _fmt(p["pose_agreement"], 2),
            p["point_count"]))

    if failed:
        out += ["", "**Captures that did not produce a model.** They are part of the",
                "campaign's result, not omissions from it — a reference distribution",
                "that silently drops its hard cases describes an easier corpus than the",
                "one that was run.", "",
                "| capture | what happened |", "| --- | --- |"]
        for r in sorted(failed, key=lambda r: r["capture"]):
            out.append(f"| {r['capture']} | `{r['error'][:160]}` |")

    if gt_rows:
        out += ["", "## Ground truth, beside the internal readings",
                "",
                "**Used once, to check whether the internal readings track true error.**",
                "Ground truth can never be a rung: the profile has to work on captures",
                "that have none, and every column above is computable without it. Both",
                "benchmark families ship reference poses — DTU as per-position projection",
                "matrices (extrinsics only; the intrinsics in use are the repository's own",
                "calibration), ETH3D as COLMAP `images.txt`.",
                "",
                "Error is the median over image PAIRS of the relative rotation and the",
                "relative translation DIRECTION, both gauge-free. Absolute poses would need",
                "an alignment whose residual is itself a free parameter.",
                "",
                "| capture | GT rot (deg) | GT transl (deg) | pairs | pose rung (deg) |",
                "| --- | --- | --- | --- | --- |"]
        for r in sorted(gt_rows, key=lambda r: r["capture"]):
            g = r["gt"]
            out.append("| {} | {} | {} | {} | {} |".format(
                r["capture"], _fmt(g.get("gt_rotation_deg"), 3),
                _fmt(g.get("gt_translation_deg"), 3), g.get("gt_pairs"),
                _fmt(r["profile"]["pose_agreement"], 3)))

    if len(gt_rows) >= 5:
        by_reg = sorted(gt_rows, key=lambda r: r["profile"]["registration"])
        starved = [r for r in by_reg if r["gt"].get("gt_pairs", 0) <= 3]
        full = [r for r in by_reg if r["profile"]["registration"] >= 0.99]
        out += ["", "### What the ground truth actually established",
                "",
                "**Not what it was computed for.** The intent was to check whether each",
                "internal rung orders captures the way true pose error does. It cannot,",
                "and the reason is worth more than the intended result.",
                "",
                "Ground-truth error here is a median over the image PAIRS a model",
                "registered. A model that registers two images has exactly one pair to",
                "be wrong about; a complete model has hundreds, including every hard",
                "one. So the measure is not comparable across models of differing",
                "completeness — and the corpus contains that comparison in its sharpest",
                "form:",
                "",
                "| capture | registered | GT rotation error | pairs compared |",
                "| --- | --- | --- | --- |"]
        for r in starved + full[:3]:
            g, pr = r["gt"], r["profile"]
            out.append("| {} | {} | {}° | {} |".format(
                r["capture"], _fmt(pr["registration"], 2),
                _fmt(g.get("gt_rotation_deg"), 2), g.get("gt_pairs")))
        # State the comparison as counted, not as remembered: the claim is that
        # a starved model OUTSCORES complete ones on truth, and the number of
        # complete models it outscores is the evidence for it.
        beat = 0
        for s in starved:
            sg = s["gt"].get("gt_rotation_deg")
            if sg is None or sg != sg:
                continue
            beat = max(beat, sum(1 for f in full
                                 if (f["gt"].get("gt_rotation_deg") or 0) >= sg))
        out += ["",
                f"**Two of the three models that abandoned most of their capture "
                f"score at least as well on ground truth as "
                f"{'all' if beat == len(full) else beat} "
                f"{len(full)} fully-registered reconstructions here.** Each kept two "
                f"images, got the one surviving pair nearly right, and is rewarded "
                f"for it by a measure that never asks what happened to the other "
                f"forty.",
                "",
                "That is the ladder's first rung — *registration is a precondition, not",
                "a tiebreak; error improves as cameras drop out because a smaller model",
                "is an easier one* — demonstrated against ground truth rather than",
                "argued from internal metrics. It is the strongest evidence in this",
                "corpus for why the profile is a VECTOR with registration first, and",
                "why a single accuracy number is not a substitute for it.",
                "",
                "**So the rank correlations between each rung and GT error are",
                "confounded and are deliberately not reported as a validation.**",
                "Computed anyway they are mostly weak and two run opposite to their",
                "expected sign, which is what the confound predicts: the rungs that",
                "most clearly separate a broken model from a good one are exactly the",
                "ones the GT measure cannot see past.",
                "",
                "**What would validate a rung**, and what Phase B is shaped to produce:",
                "two models of the SAME capture at EQUAL registration, where the GT",
                "comparison is legitimate and the rung either orders them the way truth",
                "does or does not."]

    out += ["", "## What this campaign is for",
            "",
            "The columns above are the reference distribution a new reconstruction's",
            "health profile is scored against, generated into `reference_profile.yaml`",
            "beside this file and read by the run-summary health digest. Every value is",
            "an **observed reading over this corpus**, never a threshold: a capture below",
            "the minimum here is outside the observed range, which is not the same as",
            "failing, because the minimum is the smallest of N draws.",
            ""]
    return "\n".join(out)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("results", type=Path)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args(argv)

    rows = json.loads(args.results.read_text())
    ok = [r for r in rows if "profile" in r]
    if not ok:
        print("no completed captures", file=sys.stderr)
        return 1

    md = campaign_md(rows, image_digests(args.results.parent, rows))
    yml = reference_yaml(ok)
    if args.dry_run:
        print(md)
        print("\n--- reference_profile.yaml ---\n")
        print(yml)
        return 0

    (EVIDENCE / "reference-pipeline-2026-09.md").write_text(md)
    (EVIDENCE / "reference_profile.yaml").write_text(yml)
    print(f"wrote {EVIDENCE/'reference-pipeline-2026-09.md'}")
    print(f"wrote {EVIDENCE/'reference_profile.yaml'}  ({len(ok)} captures)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
